// rules/components/index.js — barrel export for all arena components
export { Position } from './Position.js';
export { Velocity } from './Velocity.js';
export { Facing } from './Facing.js';
export { Collider } from './Collider.js';
export { Health } from './Health.js';
export { Speed } from './Speed.js';
export { Input } from './Input.js';
export { Actor, ActorKind } from './Actor.js';
export { FOV } from './FOV.js';
export { Lifetime } from './Lifetime.js';
export { Projectile } from './Projectile.js';
export { Knockback } from './Knockback.js';
export { Cooldown } from './Cooldown.js';
export { Spawn } from './Spawn.js';
export { PointLight } from './PointLight.js';
export { AI, AIBehavior } from './AI.js';
export { Inventory } from './Inventory.js';
export { ItemInfo, ItemSlot } from './ItemInfo.js';
export { PlayerTag } from './PlayerTag.js';
export { Spellbook, SpellId } from './Spellbook.js';
